# fly.toml file generated for chatfiles-test on 2023-04-09T21:34:21+08:00

app = "chatfiles"
kill_signal = "SIGINT"
kill_timeout = 60
mounts = []
primary_region = "lax"
processes = []

[[services]]
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
